// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/LexerParserRobot202120.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class LexerParserRobot202120 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static String currentString=null;
  static {
    int $line=0;
    $line=4;
    $try:try {
      currentString=$defaultValue(String.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static GArrayList images=null;
  static {
    int $line=0;
    $line=5;
    $try:try {
      images=$invokeConstructor(GArrayList.class,new Object[]{});
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static ISet allSymbols=null;
  static {
    int $line=0;
    $line=7;
    $try:try {
      allSymbols=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static ISet keyWords=null;
  static {
    int $line=0;
    $line=8;
    $try:try {
      keyWords=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static ISet skipChars=null;
  static {
    int $line=0;
    $line=9;
    $try:try {
      skipChars=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static ISet preKW=null;
  static {
    int $line=0;
    $line=12;
    $try:try {
      preKW=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static ISet preOps=null;
  static {
    int $line=0;
    $line=13;
    $try:try {
      preOps=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static ISet StartOps=null;
  static {
    int $line=0;
    $line=15;
    $try:try {
      StartOps=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static ISet Symbols1=null;
  static {
    int $line=0;
    $line=16;
    $try:try {
      Symbols1=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static ISet CharsSymbols1=null;
  static {
    int $line=0;
    $line=18;
    $try:try {
      CharsSymbols1=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static ISet alphaUpper=null;
  static {
    int $line=0;
    $line=20;
    $try:try {
      alphaUpper=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static ISet alphaLower=null;
  static {
    int $line=0;
    $line=21;
    $try:try {
      alphaLower=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static ISet digits=null;
  static {
    int $line=0;
    $line=22;
    $try:try {
      digits=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static ISet alphaNum=null;
  static {
    int $line=0;
    $line=24;
    $try:try {
      alphaNum=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static ISet Out=null;
  static {
    int $line=0;
    $line=26;
    $try:try {
      Out=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static Boolean diffIdents=null;
  static {
    int $line=0;
    $line=27;
    $try:try {
      diffIdents=$defaultValue(Boolean.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static ISet Ids=null;
  static {
    int $line=0;
    $line=29;
    $try:try {
      Ids=$defaultValue(ISet.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static GHashTableMap translation=null;
  static {
    int $line=0;
    $line=30;
    $try:try {
      translation=$invokeConstructor(GHashTableMap.class,new Object[]{});
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,null,$line);
    }
  }
  public static Object chars(Object string) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v1=$newSet();
      int $v3=$int(0);
      int $v4=$int($invokeMethod("length",string,new Object[]{}))-1;
      $v2:for (int i=$v3; i<=$v4; i++) {
        $v1.add($invokeMethod("charAt",string,new Object[]{i}));
      }
      $result=$v1;
      if (true) break $try;
      $line=32;
      $rethrow(new RuntimeException("The function \"chars(string:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"chars",$line);
    }
    return $result;
  }
  public static Object charsStrings(Object strings) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v5=$newSet(GCollections.emptySet());
      $v6:for (Object s:GCollections.unmodifiableCollection(strings)) {
        $v5.union(GCollections.unmodifiableSet(((java.lang.Iterable)(LexerParserRobot202120.chars(s)))));
      }
      $result=$v5;
      if (true) break $try;
      $line=35;
      $rethrow(new RuntimeException("The function \"charsStrings(strings:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"charsStrings",$line);
    }
    return $result;
  }
  public static Object elements(Object array) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v7=$newSet();
      int $v9=$int(0);
      int $v10=$int($opAbsolY(array))-1;
      $v8:for (int i=$v9; i<=$v10; i++) {
        $v7.add($getArrayValue(array,new Object[]{i}));
      }
      $result=$v7;
      if (true) break $try;
      $line=38;
      $rethrow(new RuntimeException("The function \"elements(array:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"elements",$line);
    }
    return $result;
  }
  public static Object prefixes(Object string) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v11=$newSet();
      int $v13=$int(1);
      int $v14=$int($invokeMethod("length",string,new Object[]{}));
      $v12:for (int i=$v13; i<=$v14; i++) {
        $v11.add($invokeMethod("substring",string,new Object[]{0,i}));
      }
      $result=$v11;
      if (true) break $try;
      $line=40;
      $rethrow(new RuntimeException("The function \"prefixes(string:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"prefixes",$line);
    }
    return $result;
  }
  public static Object splits(Object string) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v15=$newSet();
      int $v17=$int(1);
      int $v18=$int($opSubtrY($invokeMethod("length",string,new Object[]{}),1));
      $v16:for (int i=$v17; i<=$v18; i++) {
        $v15.add(GCollections.asList($invokeMethod("substring",string,new Object[]{0,i}),$invokeMethod("substring",string,new Object[]{i,$invokeMethod("length",string,new Object[]{})})));
      }
      $result=$v15;
      if (true) break $try;
      $line=41;
      $rethrow(new RuntimeException("The function \"splits(string:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"splits",$line);
    }
    return $result;
  }
  public static Object allPrefixes(Object strings) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v19=$newSet(GCollections.emptySet());
      $v20:for (Object s:GCollections.unmodifiableCollection(strings)) {
        $v19.union(GCollections.unmodifiableSet(((java.lang.Iterable)(LexerParserRobot202120.prefixes(s)))));
      }
      $result=$v19;
      if (true) break $try;
      $line=43;
      $rethrow(new RuntimeException("The function \"allPrefixes(strings:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"allPrefixes",$line);
    }
    return $result;
  }
  public static Object translationGet(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $result=(($bool((($opEqualY($opAbsolY(q),1)&&$opMembrY(q,Symbols1))&&!$opEqualY(q,'\n'))))?(q):(((gold.structures.map.GHashTableMap)translation).get(q)));
      if (true) break $try;
      $line=45;
      $rethrow(new RuntimeException("The function \"translationGet(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"translationGet",$line);
    }
    return $result;
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=48;
      currentString=$cast(String.class,$fix(""));
      $line=49;
      Object lexer=$fix(LexerParserRobot202120.createTransducer());
      $line=50;
      Object parser=$fix(LexerParserRobot202120.createAutomaton());
      $line=52;
      LexerParserRobot202120.testLexer($cast(gold.structures.automaton.ITransducer.class,lexer));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"main",$line);
    }
  }
  public static Object testLexer(ITransducer M) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=59;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=60;
      String string=null;
      string=$defaultValue(String.class);
      $line=64;
      Object inputA=$fix(LexerParserRobot202120.elements(((gold.structures.automaton.ITransducer)M).getInputAlphabet()));
      $line=67;
      Object input=$fix("");
      $line=70;
      System.out.println($message(new Object[]{"----------------------------"}));
      $line=71;
      System.out.println($message(new Object[]{"Enter one or more lines. End with a single line with $"}));
      $line=72;
      System.out.println($message(new Object[]{"If you want to stop testing, enter EXIT"}));
      $line=73;
      string=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
      $line=78;
      while (true) {
        if (!(!$opEqualY(string,"EXIT"))) break;
        $line=80;
        string=$cast(String.class,$fix($opAdditY(string," \n ")));
        $line=81;
        input=$fix("");
        $line=82;
        while (true) {
          if (!(!$opEqualY(((java.lang.String)string).charAt($int(0)),'$'))) break;
          $line=83;
          input=$fix($opAdditY(input,string));
          $line=84;
          string=$cast(String.class,$fix($opAdditY(((java.util.Scanner)sc).nextLine()," \n  ")));
        }
        $line=87;
        if ($opSbsetY(LexerParserRobot202120.chars(input),inputA)) {
          $line=88;
          currentString=$cast(String.class,$fix(""));
          $line=89;
          images=$cast(GArrayList.class,$fix($invokeConstructor(GArrayList.class,new Object[]{})));
          $line=90;
          Object result=$fix(((gold.structures.automaton.ITransducer)M).acceptsString($cast(java.lang.String.class,input)));
          $line=91;
          Object tokenStream=$fix(((gold.structures.automaton.ITransducer)M).getOutputString());
          $line=94;
          System.out.println($message(new Object[]{$opAdditY($opAdditY("The input was ",(($bool(result))?(""):("not ")))," accepted by the lexer.")}));
          $line=95;
          if ($bool(result)) {
            $line=96;
            System.out.println($message(new Object[]{$opAdditY("Token Stream:  ",tokenStream)}));
            $line=97;
            System.out.println($message(new Object[]{$opAdditY("Strings: ",images)}));
          }
          else {
            $line=99;
            System.out.println($message(new Object[]{$opAdditY("Partial token Stream ",tokenStream)}));
          }
        }
        else {
          $line=101;
          System.out.println($message(new Object[]{$opAdditY("Input contains invalid characters: ",$opDiffeY(LexerParserRobot202120.chars(input),inputA))}));
        }
        $line=103;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=105;
        System.out.println($message(new Object[]{"Enter one or more lines. End with a single line with $"}));
        $line=106;
        System.out.println($message(new Object[]{"If you want to stop testing, enter EXIT"}));
        $line=107;
        string=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
      }
      $line=110;
      System.out.println($message(new Object[]{"Good bye"}));
      $line=111;
      System.out.println($message(new Object[]{""}));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"testLexer",$line);
    }
    return $result;
  }
  public static Object problems(String q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=123;
      if ($opMembrY(q,allSymbols)) {
        $line=123;
        $result=false;
        if (true) break $try;
      }
      else {
        $line=124;
        if ($opLessqY($opAbsolY(q),1)) {
          $line=124;
          $result=true;
          if (true) break $try;
        }
        else {
          $line=126;
          for (Object $v21:GCollections.unmodifiableCollection(LexerParserRobot202120.splits(q))) {
            java.util.Iterator $v22=GCollections.unmodifiableCollection($v21).iterator();
            Object s=$v22.next();
            Object t=$v22.next();
            $line=127;
            if ((!$bool(LexerParserRobot202120.problems($cast(java.lang.String.class,s)))&&!$bool(LexerParserRobot202120.problems($cast(java.lang.String.class,t))))) {
              $line=127;
              $result=false;
              if (true) break $try;
            }
          }
          $line=129;
          $result=true;
          if (true) break $try;
        }
      }
      $line=132;
      $rethrow(new RuntimeException("The function \"problems(q:String)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"problems",$line);
    }
    return $result;
  }
  public static Object translationPreOps(Object state) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=138;
      Object x=null;
      Object y=null;
      $line=139;
      String q=null;
      q=$defaultValue(String.class);
      $line=140;
      q=$cast(String.class,$fix(state));
      $line=141;
      Object n=$fix(((java.lang.String)q).length());
      $line=142;
      if ($opEqualY(n,0)) {
        $line=142;
        $result="";
        if (true) break $try;
      }
      else {
        $line=143;
        if ($opMembrY(q,allSymbols)) {
          $line=144;
          ((gold.structures.list.GArrayList)images).add(q);
          $line=145;
          $result=LexerParserRobot202120.translationGet(q);
          if (true) break $try;
        }
        else {
          $line=146;
          if ($opEqualY(n,1)) {
            $line=146;
            $result="";
            if (true) break $try;
          }
          else {
            $line=148;
            for (Object $v23:GCollections.unmodifiableCollection(LexerParserRobot202120.splits(q))) {
              java.util.Iterator $v24=GCollections.unmodifiableCollection($v23).iterator();
              Object s=$v24.next();
              Object t=$v24.next();
              $line=149;
              x=$fix(LexerParserRobot202120.translationPreOps(s));
              $line=150;
              y=$fix(LexerParserRobot202120.translationPreOps(t));
              $line=151;
              if ((!$opEqualY(x,"")&&!$opEqualY(y,""))) {
                $line=152;
                $result=$opAdditY(x,y);
                if (true) break $try;
              }
            }
            $line=155;
            $result="";
            if (true) break $try;
          }
        }
      }
      $line=159;
      $rethrow(new RuntimeException("The function \"translationPreOps(state:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"translationPreOps",$line);
    }
    return $result;
  }
  public static Object initialize() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=170;
      skipChars=$cast(ISet.class,$fix(GCollections.asSet(' ','\t')));
      $line=171;
      alphaUpper=$cast(ISet.class,$fix($opIntvlY('A','Z')));
      $line=173;
      alphaLower=$cast(ISet.class,$fix($opIntvlY('a','z')));
      $line=174;
      digits=$cast(ISet.class,$fix($opIntvlY('0','9')));
      $line=175;
      alphaNum=$cast(ISet.class,$fix($opUnionY($opUnionY($opUnionY(alphaUpper,alphaLower),digits),GCollections.asSet('?'))));
      $line=176;
      keyWords=$cast(ISet.class,$fix(GCollections.asSet("MOVE","ROTATE","RIGHT","LEFT","LOOK","FREE","DROP","PICK","POP","CHECK","NOP","BLOCKEDP","IF","DEFINE","REPEAT","TO","BLOCK","OUTPUT","END","N","S","W","E","C","B")));
      $line=179;
      allSymbols=$cast(ISet.class,$fix(GCollections.asSet("(",")","\n","]","[","!")));
      $line=192;
      ((gold.structures.map.GHashTableMap)translation).put("\n",'\u22C8');
      $line=194;
      ((gold.structures.map.GHashTableMap)translation).put("N",'N');
      $line=195;
      ((gold.structures.map.GHashTableMap)translation).put("S",'S');
      $line=196;
      ((gold.structures.map.GHashTableMap)translation).put("W",'W');
      $line=197;
      ((gold.structures.map.GHashTableMap)translation).put("E",'E');
      $line=198;
      ((gold.structures.map.GHashTableMap)translation).put("C",'C');
      $line=199;
      ((gold.structures.map.GHashTableMap)translation).put("B",'B');
      $line=201;
      ((gold.structures.map.GHashTableMap)translation).put("NOP",'K');
      $line=202;
      ((gold.structures.map.GHashTableMap)translation).put("Num",'#');
      $line=204;
      ((gold.structures.map.GHashTableMap)translation).put("MOVE",'M');
      $line=205;
      ((gold.structures.map.GHashTableMap)translation).put("RIGHT",'r');
      $line=206;
      ((gold.structures.map.GHashTableMap)translation).put("LEFT",'l');
      $line=207;
      ((gold.structures.map.GHashTableMap)translation).put("ROTATE",'R');
      $line=209;
      ((gold.structures.map.GHashTableMap)translation).put("LOOK",'L');
      $line=210;
      ((gold.structures.map.GHashTableMap)translation).put("DROP",'D');
      $line=212;
      ((gold.structures.map.GHashTableMap)translation).put("FREE",'F');
      $line=213;
      ((gold.structures.map.GHashTableMap)translation).put("PICK",'P');
      $line=214;
      ((gold.structures.map.GHashTableMap)translation).put("POP",'p');
      $line=215;
      ((gold.structures.map.GHashTableMap)translation).put("CHECK",'c');
      $line=216;
      ((gold.structures.map.GHashTableMap)translation).put("BLOCKEDP",'w');
      $line=217;
      ((gold.structures.map.GHashTableMap)translation).put("BLOCK",'b');
      $line=221;
      ((gold.structures.map.GHashTableMap)translation).put("REPEAT",'X');
      $line=225;
      ((gold.structures.map.GHashTableMap)translation).put("IF",'?');
      $line=226;
      ((gold.structures.map.GHashTableMap)translation).put("DEFINE",'d');
      $line=227;
      ((gold.structures.map.GHashTableMap)translation).put("TO",'T');
      $line=228;
      ((gold.structures.map.GHashTableMap)translation).put("OUTPUT",'O');
      $line=229;
      ((gold.structures.map.GHashTableMap)translation).put("END",'$');
      $line=233;
      ((gold.structures.map.GHashTableMap)translation).put("IdL",'v');
      $line=234;
      ((gold.structures.map.GHashTableMap)translation).put("IdU",'V');
      $line=237;
      ((gold.structures.map.GHashTableMap)translation).put("Param",'x');
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"initialize",$line);
    }
    return $result;
  }
  public static ITransducer createTransducer() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=250;
      LexerParserRobot202120.initialize();
      $line=252;
      preOps=$cast(ISet.class,$fix(LexerParserRobot202120.allPrefixes(allSymbols)));
      $line=253;
      preKW=$cast(ISet.class,$fix(LexerParserRobot202120.allPrefixes(keyWords)));
      $line=255;
      gold.structures.set.ISet $v25=$newSet(GCollections.emptySet());
      $v26:for (Object x:GCollections.unmodifiableCollection(allSymbols)) {
        $v25.union(GCollections.unmodifiableSet(((java.lang.Iterable)(GCollections.asSet($invokeMethod("charAt",x,new Object[]{0}))))));
      }
      StartOps=$cast(ISet.class,$fix($v25));
      $line=256;
      gold.structures.set.ISet $v27=$newSet(GCollections.emptySet());
      $v28:for (Object x:GCollections.unmodifiableCollection(StartOps)) {
        $v27.union(GCollections.unmodifiableSet(((java.lang.Iterable)(GCollections.asSet($opAdditY("",x))))));
      }
      Symbols1=$cast(ISet.class,$fix($opDiffeY($opInterY($v27,allSymbols),GCollections.asSet("\n"))));
      $line=257;
      gold.structures.set.ISet $v29=$newSet(GCollections.emptySet());
      $v30:for (Object x:GCollections.unmodifiableCollection(Symbols1)) {
        $v29.union(GCollections.unmodifiableSet(((java.lang.Iterable)(GCollections.asSet($invokeMethod("charAt",x,new Object[]{0}))))));
      }
      CharsSymbols1=$cast(ISet.class,$fix($v29));
      $line=260;
      gold.structures.set.ISet $v31=$newSet(GCollections.emptySet());
      $v32:for (Object x:GCollections.unmodifiableCollection(((gold.structures.map.GHashTableMap)translation).values())) {
        $v31.union(GCollections.unmodifiableSet(((java.lang.Iterable)(GCollections.asSet(x)))));
      }
      Out=$cast(ISet.class,$fix($opUnionY(CharsSymbols1,$v31)));
      $line=262;
      System.out.println($message(new Object[]{Out}));
      $line=263;
      Ids=$cast(ISet.class,$fix(GCollections.asSet("IdU","IdL","Param")));
      $line=265;
      Object Q=$fix($opUnionY($opUnionY(GCollections.asSet("INIT","IdU","Num","Err","IdL","Param"),preKW),preOps));
      $line=267;
      System.out.println($message(new Object[]{Q}));
      $line=269;
      Object \u03A3=$fix($opUnionY($opUnionY($opUnionY(alphaNum,LexerParserRobot202120.charsStrings(allSymbols)),skipChars),GCollections.asSet(':')));
      $line=273;
      Object q_0=$fix("INIT");
      $line=274;
      Object F=$fix(GCollections.asSet("INIT"));
      $line=275;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,Out,q_0,F,new GMethod(LexerParserRobot202120.class,"\u03B4"),new GMethod(LexerParserRobot202120.class,"g"),new GMethod(LexerParserRobot202120.class,"h")});
      if (true) break $try;
      $line=276;
      $rethrow(new RuntimeException("The function \"createTransducer()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"createTransducer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object state, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=281;
      String q=null;
      q=$defaultValue(String.class);
      $line=282;
      q=$cast(String.class,$fix(state));
      $line=284;
      if ($opEqualY(q,"Err")) {
        $line=284;
        $result="Err";
        if (true) break $try;
      }
      else {
        $line=285;
        if ($opMembrY(q,preOps)) {
          $line=286;
          if ($opMembrY($opAdditY(q,\u03C3),preOps)) {
            $line=286;
            $result=$opAdditY(q,\u03C3);
            if (true) break $try;
          }
          else {
            $line=287;
            if ($bool(LexerParserRobot202120.problems($cast(java.lang.String.class,q)))) {
              $line=287;
              $result="Err";
              if (true) break $try;
            }
            else {
              $line=288;
              if ($opMembrY(\u03C3,skipChars)) {
                $line=288;
                $result="INIT";
                if (true) break $try;
              }
              else {
                $line=289;
                if ($opMembrY(\u03C3,$opIntvlY('0','9'))) {
                  $line=289;
                  $result="Num";
                  if (true) break $try;
                }
                else {
                  $line=290;
                  if ($opMembrY($opAdditY("",\u03C3),preKW)) {
                    $line=290;
                    $result=$opAdditY("",\u03C3);
                    if (true) break $try;
                  }
                  else {
                    $line=291;
                    if ($opMembrY(\u03C3,alphaUpper)) {
                      $line=291;
                      $result="IdU";
                      if (true) break $try;
                    }
                    else {
                      $line=292;
                      if ($opMembrY(\u03C3,alphaLower)) {
                        $line=292;
                        $result="IdL";
                        if (true) break $try;
                      }
                      else {
                        $line=293;
                        if ($opMembrY($opAdditY("",\u03C3),preOps)) {
                          $line=293;
                          $result=$opAdditY("",\u03C3);
                          if (true) break $try;
                        }
                        else {
                          $line=294;
                          $result="Err";
                          if (true) break $try;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        else {
          $line=296;
          if ($opMembrY(\u03C3,skipChars)) {
            $line=296;
            $result="INIT";
            if (true) break $try;
          }
          else {
            $line=297;
            if (($opEqualY(q,"INIT")&&$opMembrY(\u03C3,$opIntvlY('0','9')))) {
              $line=297;
              $result="Num";
              if (true) break $try;
            }
            else {
              $line=298;
              if (($opEqualY(q,"INIT")&&$opMembrY($opAdditY("",\u03C3),preKW))) {
                $line=298;
                $result=$opAdditY("",\u03C3);
                if (true) break $try;
              }
              else {
                $line=299;
                if (($opEqualY(q,"INIT")&&$opMembrY(\u03C3,alphaUpper))) {
                  $line=299;
                  $result="IdU";
                  if (true) break $try;
                }
                else {
                  $line=300;
                  if (($opEqualY(q,"INIT")&&$opMembrY(\u03C3,alphaLower))) {
                    $line=300;
                    $result="IdL";
                    if (true) break $try;
                  }
                  else {
                    $line=301;
                    if (($opEqualY(q,"INIT")&&$opEqualY(\u03C3,':'))) {
                      $line=301;
                      $result="Param";
                      if (true) break $try;
                    }
                    else {
                      $line=302;
                      if (($opEqualY(q,"INIT")&&$opMembrY($opAdditY("",\u03C3),preOps))) {
                        $line=302;
                        $result=$opAdditY("",\u03C3);
                        if (true) break $try;
                      }
                      else {
                        $line=303;
                        if (($opMembrY(q,preKW)&&$opMembrY($opAdditY(q,\u03C3),preKW))) {
                          $line=303;
                          $result=$opAdditY(q,\u03C3);
                          if (true) break $try;
                        }
                        else {
                          $line=304;
                          if ((($opMembrY(q,preKW)&&$opMembrY(\u03C3,alphaNum))&&$opMembrY(((java.lang.String)q).charAt($int(0)),alphaUpper))) {
                            $line=304;
                            $result="IdU";
                            if (true) break $try;
                          }
                          else {
                            $line=305;
                            if ((($opMembrY(q,preKW)&&$opMembrY(\u03C3,alphaNum))&&$opMembrY(((java.lang.String)q).charAt($int(0)),alphaLower))) {
                              $line=305;
                              $result="IdL";
                              if (true) break $try;
                            }
                            else {
                              $line=306;
                              if (($opMembrY(q,preKW)&&$opMembrY($opAdditY("",\u03C3),preOps))) {
                                $line=306;
                                $result=$opAdditY("",\u03C3);
                                if (true) break $try;
                              }
                              else {
                                $line=307;
                                if (($opEqualY(q,"Num")&&$opMembrY(\u03C3,$opIntvlY('0','9')))) {
                                  $line=307;
                                  $result="Num";
                                  if (true) break $try;
                                }
                                else {
                                  $line=308;
                                  if (($opEqualY(q,"Num")&&$opMembrY($opAdditY("",\u03C3),preOps))) {
                                    $line=308;
                                    $result=$opAdditY("",\u03C3);
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=309;
                                    if (($opEqualY(q,"Num")&&$opMembrY(\u03C3,alphaNum))) {
                                      $line=309;
                                      $result="Err";
                                      if (true) break $try;
                                    }
                                    else {
                                      $line=310;
                                      if (($opMembrY(q,Ids)&&$opMembrY(\u03C3,alphaNum))) {
                                        $line=310;
                                        $result=q;
                                        if (true) break $try;
                                      }
                                      else {
                                        $line=311;
                                        if (($opMembrY(q,Ids)&&$opMembrY($opAdditY("",\u03C3),preOps))) {
                                          $line=311;
                                          $result=$opAdditY("",\u03C3);
                                          if (true) break $try;
                                        }
                                        else {
                                          $line=312;
                                          $result="Err";
                                          if (true) break $try;
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=314;
      $rethrow(new RuntimeException("The function \"\u03B4(state:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=320;
      $result="";
      if (true) break $try;
      $line=321;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"g",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=324;
      String s=null;
      s=$defaultValue(String.class);
      $line=327;
      s=$cast(String.class,$fix((($bool($opEqualY(\u03C3,'\n')))?("\\n"):($opAdditY("",\u03C3)))));
      $line=330;
      if ($opMembrY(q,preOps)) {
        $line=331;
        if (($opMembrY(\u03C3,skipChars)&&$opMembrY(q,allSymbols))) {
          $line=332;
          ((gold.structures.list.GArrayList)images).add(currentString);
          $line=333;
          currentString=$cast(String.class,$fix(""));
          $line=334;
          $result=LexerParserRobot202120.translationGet(q);
          if (true) break $try;
        }
        else {
          $line=335;
          if ($opMembrY($opAdditY(q,\u03C3),preOps)) {
            $line=336;
            currentString=$cast(String.class,$fix($opAdditY(currentString,s)));
            $line=337;
            $result="";
            if (true) break $try;
          }
          else {
            $line=338;
            if (($opMembrY(\u03C3,$opUnionY(StartOps,alphaNum))&&$opMembrY(q,allSymbols))) {
              $line=339;
              ((gold.structures.list.GArrayList)images).add(currentString);
              $line=340;
              currentString=$cast(String.class,$fix($opAdditY("",s)));
              $line=341;
              $result=LexerParserRobot202120.translationGet(q);
              if (true) break $try;
            }
            else {
              $line=342;
              if ($opMembrY(\u03C3,$opUnionY($opUnionY(StartOps,alphaNum),skipChars))) {
                $line=343;
                currentString=$cast(String.class,$fix($opAdditY("",s)));
                $line=344;
                $result=LexerParserRobot202120.translationPreOps(q);
                if (true) break $try;
              }
              else {
                $line=346;
                currentString=$cast(String.class,$fix($opAdditY(currentString,s)));
                $line=347;
                $result="";
                if (true) break $try;
              }
            }
          }
        }
      }
      else {
        $line=351;
        if ((!$opMembrY(q,GCollections.asSet("Err"))&&$opMembrY(\u03C3,$opUnionY(skipChars,StartOps)))) {
          $line=352;
          if ($opEqualY(q,"INIT")) {
            $line=353;
            currentString=$cast(String.class,$fix((($bool($opMembrY(\u03C3,StartOps)))?(s):(""))));
            $line=354;
            $result="";
            if (true) break $try;
          }
          else {
            $line=355;
            if ($opEqualY(LexerParserRobot202120.translationGet(q),null)) {
              $line=359;
              ((gold.structures.list.GArrayList)images).add(currentString);
              $line=360;
              currentString=$cast(String.class,$fix((($bool($opMembrY(\u03C3,$opUnionY(skipChars,StartOps))))?(s):(""))));
              $line=362;
              Object f=$fix($invokeMethod("charAt",q,new Object[]{0}));
              $line=363;
              if ($opMembrY(f,alphaUpper)) {
                $line=363;
                $result=LexerParserRobot202120.translationGet("IdU");
                if (true) break $try;
              }
              else {
                $line=365;
                $result=LexerParserRobot202120.translationGet("IdL");
                if (true) break $try;
              }
            }
            else {
              $line=369;
              ((gold.structures.list.GArrayList)images).add(currentString);
              $line=370;
              currentString=$cast(String.class,$fix((($bool($opMembrY(\u03C3,$opUnionY(skipChars,StartOps))))?(s):(""))));
              $line=371;
              $result=LexerParserRobot202120.translationGet(q);
              if (true) break $try;
            }
          }
        }
        else {
          $line=377;
          currentString=$cast(String.class,$fix($opAdditY(currentString,s)));
          $line=378;
          $result="";
          if (true) break $try;
        }
      }
      $line=381;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"h",$line);
    }
    return $result;
  }
  public static IPushdownAutomaton createAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=386;
      Object Q=$fix(GCollections.asSet(0,1,2));
      $line=387;
      Object \u03A3=$fix(Out);
      $line=388;
      Object \u0393=$fix(GCollections.asSet('1'));
      $line=389;
      Object q_0=$fix(0);
      $line=390;
      Object F=$fix(GCollections.asSet(0));
      $line=391;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=393;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,0,$cast(java.lang.String.class,'\u22C8')),new Object[]{});
      $line=394;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,'R')),new Object[]{});
      $line=395;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,'#')),new Object[]{});
      $line=396;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,'V')),new Object[]{});
      $line=397;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,'v')),new Object[]{});
      $line=398;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,'x')),new Object[]{});
      $line=399;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,0,$cast(java.lang.String.class,'\u22C8')),new Object[]{});
      $line=402;
      $result=M;
      if (true) break $try;
      $line=403;
      $rethrow(new RuntimeException("The function \"createAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"createAutomaton",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
  public static Object testLexerParser(ITransducer M, IPushdownAutomaton P) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=407;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=408;
      String string=null;
      string=$defaultValue(String.class);
      $line=412;
      Object inputA=$fix(LexerParserRobot202120.elements(((gold.structures.automaton.ITransducer)M).getInputAlphabet()));
      $line=415;
      Object input=$fix("");
      $line=418;
      System.out.println($message(new Object[]{"----------------------------"}));
      $line=419;
      System.out.println($message(new Object[]{"Enter one or more lines. End with a single line with $"}));
      $line=420;
      System.out.println($message(new Object[]{"If you want to stop testing, enter EXIT"}));
      $line=421;
      string=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
      $line=426;
      while (true) {
        if (!(!$opEqualY(string,"EXIT"))) break;
        $line=428;
        string=$cast(String.class,$fix($opAdditY(string,"  \n ")));
        $line=429;
        input=$fix("");
        $line=430;
        while (true) {
          if (!(!$opEqualY(((java.lang.String)string).charAt($int(0)),'$'))) break;
          $line=431;
          input=$fix($opAdditY(input,string));
          $line=432;
          string=$cast(String.class,$fix($opAdditY(((java.util.Scanner)sc).nextLine()," \n ")));
        }
        $line=435;
        if ($opSbsetY(LexerParserRobot202120.chars(input),inputA)) {
          $line=436;
          currentString=$cast(String.class,$fix(""));
          $line=437;
          images=$cast(GArrayList.class,$fix($invokeConstructor(GArrayList.class,new Object[]{})));
          $line=438;
          Object result=$fix(((gold.structures.automaton.ITransducer)M).acceptsString($cast(java.lang.String.class,input)));
          $line=439;
          Object tokenStream=$fix(((gold.structures.automaton.ITransducer)M).getOutputString());
          $line=441;
          System.out.println($message(new Object[]{$opAdditY($opAdditY("The input was ",(($bool(result))?(""):("not ")))," accepted by the lexer.")}));
          $line=442;
          if ($bool(result)) {
            $line=443;
            System.out.println($message(new Object[]{$opAdditY("Token Stream:  ",tokenStream)}));
            $line=444;
            System.out.println($message(new Object[]{$opAdditY("Strings: ",images)}));
            $line=445;
            result=$fix(((gold.structures.automaton.IPushdownAutomaton)P).acceptsString($cast(java.lang.String.class,tokenStream)));
            $line=446;
            System.out.println($message(new Object[]{$opAdditY("Parser result: ",(($bool(result))?("accepted "):("rejected ")))}));
          }
          else {
            $line=448;
            System.out.println($message(new Object[]{$opAdditY("Partial token Stream ",tokenStream)}));
          }
        }
        else {
          $line=450;
          System.out.println($message(new Object[]{$opAdditY("Input contains invalid characters: ",$opDiffeY(LexerParserRobot202120.chars(input),inputA))}));
        }
        $line=452;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=454;
        System.out.println($message(new Object[]{"Enter one or more lines. End with a single line with $"}));
        $line=455;
        System.out.println($message(new Object[]{"If you want to stop testing, enter EXIT"}));
        $line=456;
        string=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
      }
      $line=459;
      System.out.println($message(new Object[]{"Good bye"}));
      $line=460;
      System.out.println($message(new Object[]{""}));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202120.class,"testLexerParser",$line);
    }
    return $result;
  }
}
